services:
  - type: web
    name: forge-backend
    env: docker
    dockerfilePath: apps/server/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: forge-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: forge-redis
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "4000"
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: NEXT_PUBLIC_APP_URL
        value: "https://coders-league-zeta.vercel.app"
      - key: PISTON_URL
        value: "https://emkc.org/api/v2/piston"
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false

  - type: redis
    name: forge-redis
    plan: free
    ipAllowList: []

databases:
  - name: forge-db
    plan: free
